---

- hosts: all
  become: true
  tasks:

  - name: install python3
    yum:
      name: python3

  - name: http
    yum:
      name: httpd

  - name: yum update
    yum:
      name: '*' 
      state: latest
      update_cache: yes
