---

- hosts: all
  become: true
  tasks:

  - name: install python3
    yum:
      name: python3
    when: ansible_distribution == "CentOS"

  - name: http
    yum:
      name: httpd

  - name: yum update
    yum:
      name: '*' 
      state: latest
      update_cache: yes


  - name: start httpd
    shell: "systemctl start httpd"
     # "firewall-cmd --add-port=80/tcp"
    become: True
    become_user: root

  - name: open firewall port 80
    shell: "firewall-cmd --add-port=80/tcp"
    become: True
    become_user: root

  - name: copy default html file for website
    tags: httpd, apache
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

